import EconHDFE.PartitionRefinement
import EconHDFE.WeightedLeastSquares
import EconHDFE.ResidualCore
import EconHDFE.CategoricalDesign
import EconHDFE.PeelingProjection
import EconHDFE.PeelingTermination
import EconHDFE.CategoricalRecode
import EconHDFE.PeelingExamples
